// Shared data file - themes, dinosaurs, and utilities used across all pages

export interface Dinosaur {
  name: string
  value: number | string
  rarity?: string
  code?: string
  sdna?: string
  tier?: string
}

export interface Tier {
  name: string
  range: string
  color: string
  gradient: string
  dinosaurs: Dinosaur[]
}

export interface Theme {
  name: string
  background: string
  cardBg: string
  cardBorder: string
  headerBg: string
  textPrimary: string
  textSecondary: string
  textAccent: string
  border: string
  buttonBg: string
  buttonHover: string
  buttonText: string
  inputBg: string
  inputBorder: string
  badgeBg: string
  badgeText: string
  scrollHeaderBg: string
  dropdownBg: string
  linkHover: string
  rarityColors: {
    "8/8": string
    "7/8": string
    "6/8": string
    "5/8": string
    "4/8": string
    "3/8": string
    "2/8": string
    "1/8": string
  }
}

// DNA conversion rate (DNA per 1 value)
export const DNA_CONVERSION_MIN = 23000
export const DNA_CONVERSION_MAX = 25000

// ─── Themes ────────────────────────────────────────────────────
export const themes: Record<string, Theme> = {
  dark: {
    name: "Dark Mode",
    background: "bg-[#0a0a0f]",
    cardBg: "bg-[#12121a]/80",
    cardBorder: "border-[#1e1e2e]/80",
    headerBg: "bg-[#0a0a0f]/90",
    textPrimary: "text-[#e4e4ef]",
    textSecondary: "text-[#8888a0]",
    textAccent: "text-[#60a5fa]",
    border: "border-[#1e1e2e]",
    buttonBg: "bg-[#1a1a28]",
    buttonHover: "hover:bg-[#252538]",
    buttonText: "text-[#c4c4d8]",
    inputBg: "bg-[#0e0e18]",
    inputBorder: "border-[#2a2a3e]",
    badgeBg: "bg-[#1e1e2e]",
    badgeText: "text-[#d4d4e8]",
    scrollHeaderBg: "bg-[#0a0a0f]/98",
    dropdownBg: "bg-[#12121a]",
    linkHover: "hover:text-[#93c5fd]",
    rarityColors: {
      "8/8": "bg-purple-600 text-white border-purple-500",
      "7/8": "bg-red-600 text-white border-red-500",
      "6/8": "bg-orange-500 text-white border-orange-400",
      "5/8": "bg-yellow-500 text-black border-yellow-400",
      "4/8": "bg-green-600 text-white border-green-500",
      "3/8": "bg-cyan-500 text-white border-cyan-400",
      "2/8": "bg-blue-600 text-white border-blue-500",
      "1/8": "bg-slate-500 text-white border-slate-400",
    },
  },
  pb: {
    name: "Pitch Black",
    background: "bg-black",
    cardBg: "bg-zinc-950/40",
    cardBorder: "border-zinc-800/60",
    headerBg: "bg-black/95",
    textPrimary: "text-zinc-100",
    textSecondary: "text-zinc-400",
    textAccent: "text-cyan-400",
    border: "border-zinc-800/60",
    buttonBg: "bg-zinc-900/60",
    buttonHover: "hover:bg-zinc-800/70",
    buttonText: "text-zinc-200",
    inputBg: "bg-zinc-950/60",
    inputBorder: "border-zinc-700/70",
    badgeBg: "bg-zinc-800/70",
    badgeText: "text-zinc-100",
    scrollHeaderBg: "bg-black/98",
    dropdownBg: "bg-black",
    linkHover: "hover:text-cyan-300",
    rarityColors: {
      "8/8": "bg-fuchsia-600 text-white border-fuchsia-500",
      "7/8": "bg-red-600 text-white border-red-500",
      "6/8": "bg-orange-600 text-white border-orange-500",
      "5/8": "bg-amber-500 text-black border-amber-400",
      "4/8": "bg-emerald-600 text-white border-emerald-500",
      "3/8": "bg-cyan-500 text-black border-cyan-400",
      "2/8": "bg-blue-600 text-white border-blue-500",
      "1/8": "bg-zinc-700 text-zinc-200 border-zinc-600",
    },
  },
  neon: {
    name: "Neon Cyber",
    background: "bg-gradient-to-br from-black via-purple-950 to-black",
    cardBg: "bg-purple-900/20",
    cardBorder: "border-purple-500/30",
    headerBg: "bg-black/40",
    textPrimary: "text-purple-100",
    textSecondary: "text-purple-300",
    textAccent: "text-pink-300",
    border: "border-purple-400/40",
    buttonBg: "bg-purple-800/40",
    buttonHover: "hover:bg-purple-700/50",
    buttonText: "text-purple-100",
    inputBg: "bg-purple-900/30",
    inputBorder: "border-purple-500/40",
    badgeBg: "bg-purple-600/50",
    badgeText: "text-purple-100",
    scrollHeaderBg: "bg-black/95",
    dropdownBg: "bg-purple-950",
    linkHover: "hover:text-pink-300",
    rarityColors: {
      "8/8": "bg-pink-500 text-white border-pink-400",
      "7/8": "bg-fuchsia-500 text-white border-fuchsia-400",
      "6/8": "bg-purple-500 text-white border-purple-400",
      "5/8": "bg-violet-500 text-white border-violet-400",
      "4/8": "bg-indigo-500 text-white border-indigo-400",
      "3/8": "bg-cyan-400 text-white border-cyan-300",
      "2/8": "bg-purple-700 text-white border-purple-600",
      "1/8": "bg-slate-600 text-white border-slate-500",
    },
  },
  arctic: {
    name: "Arctic Ice",
    background: "bg-gradient-to-br from-slate-100 via-blue-50 to-cyan-100",
    cardBg: "bg-white/70",
    cardBorder: "border-blue-200/60",
    headerBg: "bg-white/80",
    textPrimary: "text-slate-800",
    textSecondary: "text-slate-600",
    textAccent: "text-blue-700",
    border: "border-blue-300/50",
    buttonBg: "bg-blue-100/80",
    buttonHover: "hover:bg-blue-200/80",
    buttonText: "text-slate-700",
    inputBg: "bg-white/80",
    inputBorder: "border-blue-200/60",
    badgeBg: "bg-blue-200/70",
    badgeText: "text-slate-800",
    scrollHeaderBg: "bg-white/95",
    dropdownBg: "bg-white",
    linkHover: "hover:text-blue-800",
    rarityColors: {
      "8/8": "bg-indigo-600 text-white border-indigo-500",
      "7/8": "bg-blue-600 text-white border-blue-500",
      "6/8": "bg-cyan-500 text-white border-cyan-400",
      "5/8": "bg-teal-500 text-white border-teal-400",
      "4/8": "bg-emerald-500 text-white border-emerald-400",
      "3/8": "bg-sky-500 text-white border-sky-400",
      "2/8": "bg-sky-300 text-sky-800 border-sky-200",
      "1/8": "bg-slate-400 text-slate-800 border-slate-300",
    },
  },
  volcano: {
    name: "Volcanic Fire",
    background: "bg-gradient-to-br from-red-950 via-orange-950 to-yellow-950",
    cardBg: "bg-red-900/25",
    cardBorder: "border-orange-500/40",
    headerBg: "bg-red-950/60",
    textPrimary: "text-orange-100",
    textSecondary: "text-orange-300",
    textAccent: "text-yellow-300",
    border: "border-orange-400/50",
    buttonBg: "bg-red-800/50",
    buttonHover: "hover:bg-red-700/60",
    buttonText: "text-orange-100",
    inputBg: "bg-red-900/40",
    inputBorder: "border-orange-500/50",
    badgeBg: "bg-orange-600/60",
    badgeText: "text-orange-100",
    scrollHeaderBg: "bg-red-950/95",
    dropdownBg: "bg-red-950",
    linkHover: "hover:text-yellow-200",
    rarityColors: {
      "8/8": "bg-red-600 text-white border-red-500",
      "7/8": "bg-orange-600 text-white border-orange-500",
      "6/8": "bg-yellow-500 text-black border-yellow-400",
      "5/8": "bg-amber-500 text-black border-amber-400",
      "4/8": "bg-orange-700 text-white border-orange-600",
      "3/8": "bg-red-800 text-white border-red-700",
      "2/8": "bg-rose-800 text-white border-rose-700",
      "1/8": "bg-gray-600 text-white border-gray-500",
    },
  },
  forest: {
    name: "Deep Forest",
    background: "bg-gradient-to-br from-green-950 via-emerald-950 to-teal-950",
    cardBg: "bg-green-900/25",
    cardBorder: "border-emerald-500/40",
    headerBg: "bg-green-950/60",
    textPrimary: "text-emerald-100",
    textSecondary: "text-emerald-300",
    textAccent: "text-teal-300",
    border: "border-emerald-400/50",
    buttonBg: "bg-green-800/50",
    buttonHover: "hover:bg-green-700/60",
    buttonText: "text-emerald-100",
    inputBg: "bg-green-900/40",
    inputBorder: "border-emerald-500/50",
    badgeBg: "bg-emerald-600/60",
    badgeText: "text-emerald-100",
    scrollHeaderBg: "bg-green-950/95",
    dropdownBg: "bg-green-950",
    linkHover: "hover:text-teal-200",
    rarityColors: {
      "8/8": "bg-emerald-500 text-white border-emerald-400",
      "7/8": "bg-green-500 text-white border-green-400",
      "6/8": "bg-lime-500 text-black border-lime-400",
      "5/8": "bg-yellow-500 text-black border-yellow-400",
      "4/8": "bg-green-600 text-white border-green-500",
      "3/8": "bg-teal-600 text-white border-teal-500",
      "2/8": "bg-emerald-700 text-white border-emerald-600",
      "1/8": "bg-gray-600 text-white border-gray-500",
    },
  },
  ocean: {
    name: "Deep Ocean",
    background: "bg-gradient-to-br from-blue-950 via-indigo-950 to-purple-950",
    cardBg: "bg-blue-900/25",
    cardBorder: "border-blue-400/40",
    headerBg: "bg-blue-950/60",
    textPrimary: "text-blue-100",
    textSecondary: "text-blue-300",
    textAccent: "text-indigo-300",
    border: "border-blue-400/50",
    buttonBg: "bg-blue-800/50",
    buttonHover: "hover:bg-blue-700/60",
    buttonText: "text-blue-100",
    inputBg: "bg-blue-900/40",
    inputBorder: "border-blue-500/50",
    badgeBg: "bg-blue-600/60",
    badgeText: "text-blue-100",
    scrollHeaderBg: "bg-blue-950/95",
    dropdownBg: "bg-blue-950",
    linkHover: "hover:text-indigo-200",
    rarityColors: {
      "8/8": "bg-blue-500 text-white border-blue-400",
      "7/8": "bg-cyan-500 text-white border-cyan-400",
      "6/8": "bg-teal-500 text-white border-teal-400",
      "5/8": "bg-sky-500 text-white border-sky-400",
      "4/8": "bg-blue-600 text-white border-blue-500",
      "3/8": "bg-indigo-600 text-white border-indigo-500",
      "2/8": "bg-purple-600 text-white border-purple-500",
      "1/8": "bg-gray-600 text-white border-gray-500",
    },
  },
  sunset: {
    name: "Golden Sunset",
    background: "bg-gradient-to-br from-amber-100 via-orange-100 to-red-100",
    cardBg: "bg-white/80",
    cardBorder: "border-amber-300/60",
    headerBg: "bg-amber-50/80",
    textPrimary: "text-amber-900",
    textSecondary: "text-amber-700",
    textAccent: "text-orange-700",
    border: "border-amber-400/60",
    buttonBg: "bg-amber-200/80",
    buttonHover: "hover:bg-amber-300/80",
    buttonText: "text-amber-800",
    inputBg: "bg-white/90",
    inputBorder: "border-amber-300/60",
    badgeBg: "bg-amber-300/80",
    badgeText: "text-amber-900",
    scrollHeaderBg: "bg-amber-50/95",
    dropdownBg: "bg-white",
    linkHover: "hover:text-orange-800",
    rarityColors: {
      "8/8": "bg-red-500 text-white border-red-400",
      "7/8": "bg-orange-500 text-white border-orange-400",
      "6/8": "bg-amber-500 text-black border-amber-400",
      "5/8": "bg-yellow-500 text-black border-yellow-400",
      "4/8": "bg-orange-600 text-white border-orange-500",
      "3/8": "bg-red-600 text-white border-red-500",
      "2/8": "bg-rose-600 text-white border-rose-500",
      "1/8": "bg-gray-600 text-white border-gray-500",
    },
  },
  cosmic: {
    name: "Cosmic Purple",
    background: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900",
    cardBg: "bg-purple-900/20",
    cardBorder: "border-purple-400/30",
    headerBg: "bg-black/20",
    textPrimary: "text-white",
    textSecondary: "text-purple-300",
    textAccent: "text-pink-300",
    border: "border-purple-400/40",
    buttonBg: "bg-purple-800/40",
    buttonHover: "hover:bg-purple-700/50",
    buttonText: "text-white",
    inputBg: "bg-purple-900/30",
    inputBorder: "border-purple-500/40",
    badgeBg: "bg-purple-600/50",
    badgeText: "text-white",
    scrollHeaderBg: "bg-black/95",
    dropdownBg: "bg-purple-950",
    linkHover: "hover:text-pink-200",
    rarityColors: {
      "8/8": "bg-pink-500 text-white border-pink-400",
      "7/8": "bg-purple-500 text-white border-purple-400",
      "6/8": "bg-violet-500 text-white border-violet-400",
      "5/8": "bg-indigo-500 text-white border-indigo-400",
      "4/8": "bg-blue-500 text-white border-blue-400",
      "3/8": "bg-cyan-500 text-white border-cyan-400",
      "2/8": "bg-purple-700 text-white border-purple-600",
      "1/8": "bg-slate-600 text-white border-slate-500",
    },
  },
  matrix: {
    name: "Matrix",
    background: "bg-black",
    cardBg: "bg-green-950/20",
    cardBorder: "border-green-700/30",
    headerBg: "bg-black/30",
    textPrimary: "text-green-300",
    textSecondary: "text-green-500",
    textAccent: "text-lime-300",
    border: "border-green-800/50",
    buttonBg: "bg-green-900/30",
    buttonHover: "hover:bg-green-800/40",
    buttonText: "text-green-200",
    inputBg: "bg-green-950/40",
    inputBorder: "border-green-700/40",
    badgeBg: "bg-green-800/50",
    badgeText: "text-green-100",
    scrollHeaderBg: "bg-black/95",
    dropdownBg: "bg-black",
    linkHover: "hover:text-lime-200",
    rarityColors: {
      "8/8": "bg-green-400 text-black border-green-300",
      "7/8": "bg-green-500 text-black border-green-400",
      "6/8": "bg-green-600 text-white border-green-500",
      "5/8": "bg-green-700 text-white border-green-600",
      "4/8": "bg-green-800 text-white border-green-700",
      "3/8": "bg-green-900 text-white border-green-800",
      "2/8": "bg-green-950 text-white border-green-900",
      "1/8": "bg-gray-800 text-gray-400 border-gray-700",
    },
  },
  royalGold: {
    name: "Royal Gold",
    background: "bg-slate-900",
    cardBg: "bg-blue-950/30",
    cardBorder: "border-amber-500/20",
    headerBg: "bg-blue-950/40",
    textPrimary: "text-amber-100",
    textSecondary: "text-amber-300",
    textAccent: "text-yellow-200",
    border: "border-amber-400/30",
    buttonBg: "bg-amber-800/20",
    buttonHover: "hover:bg-amber-700/30",
    buttonText: "text-amber-100",
    inputBg: "bg-blue-950/50",
    inputBorder: "border-amber-500/30",
    badgeBg: "bg-amber-600/40",
    badgeText: "text-amber-100",
    scrollHeaderBg: "bg-slate-900/95",
    dropdownBg: "bg-slate-950",
    linkHover: "hover:text-yellow-100",
    rarityColors: {
      "8/8": "bg-yellow-400 text-black border-yellow-300",
      "7/8": "bg-yellow-500 text-black border-yellow-400",
      "6/8": "bg-amber-500 text-white border-amber-400",
      "5/8": "bg-amber-600 text-white border-amber-500",
      "4/8": "bg-amber-700 text-white border-amber-600",
      "3/8": "bg-amber-800 text-white border-amber-700",
      "2/8": "bg-amber-900 text-white border-amber-800",
      "1/8": "bg-slate-700 text-slate-300 border-slate-600",
    },
  },
  dusk: {
    name: "Dusk",
    background: "bg-indigo-950",
    cardBg: "bg-purple-950/30",
    cardBorder: "border-purple-800/40",
    headerBg: "bg-indigo-950/50",
    textPrimary: "text-orange-200",
    textSecondary: "text-purple-300",
    textAccent: "text-orange-300",
    border: "border-purple-700/50",
    buttonBg: "bg-purple-900/40",
    buttonHover: "hover:bg-purple-800/50",
    buttonText: "text-orange-100",
    inputBg: "bg-purple-950/50",
    inputBorder: "border-purple-700/60",
    badgeBg: "bg-orange-800/40",
    badgeText: "text-orange-100",
    scrollHeaderBg: "bg-indigo-950/95",
    dropdownBg: "bg-indigo-950",
    linkHover: "hover:text-orange-100",
    rarityColors: {
      "8/8": "bg-orange-400 text-black border-orange-300",
      "7/8": "bg-orange-500 text-white border-orange-400",
      "6/8": "bg-purple-500 text-white border-purple-400",
      "5/8": "bg-purple-600 text-white border-purple-500",
      "4/8": "bg-purple-700 text-white border-purple-600",
      "3/8": "bg-purple-800 text-white border-purple-700",
      "2/8": "bg-purple-900 text-white border-purple-800",
      "1/8": "bg-slate-700 text-slate-300 border-slate-600",
    },
  },
  solarFlare: {
    name: "Solar Flare",
    background: "bg-gray-900",
    cardBg: "bg-gray-800/50",
    cardBorder: "border-orange-500/40",
    headerBg: "bg-gray-900/60",
    textPrimary: "text-orange-300",
    textSecondary: "text-orange-500",
    textAccent: "text-yellow-400",
    border: "border-orange-400/40",
    buttonBg: "bg-orange-800/50",
    buttonHover: "hover:bg-orange-700/60",
    buttonText: "text-orange-100",
    inputBg: "bg-gray-800/70",
    inputBorder: "border-orange-500/50",
    badgeBg: "bg-orange-600/60",
    badgeText: "text-orange-100",
    scrollHeaderBg: "bg-gray-900/95",
    dropdownBg: "bg-gray-900",
    linkHover: "hover:text-yellow-300",
    rarityColors: {
      "8/8": "bg-yellow-400 text-black border-yellow-300",
      "7/8": "bg-yellow-500 text-black border-yellow-400",
      "6/8": "bg-orange-500 text-white border-orange-400",
      "5/8": "bg-orange-600 text-white border-orange-500",
      "4/8": "bg-red-600 text-white border-red-500",
      "3/8": "bg-red-700 text-white border-red-600",
      "2/8": "bg-red-800 text-white border-red-700",
      "1/8": "bg-gray-700 text-gray-300 border-gray-600",
    },
  },
  sakura: {
    name: "Sakura",
    background: "bg-indigo-900",
    cardBg: "bg-indigo-800/40",
    cardBorder: "border-pink-400/30",
    headerBg: "bg-indigo-900/60",
    textPrimary: "text-pink-100",
    textSecondary: "text-pink-200",
    textAccent: "text-white",
    border: "border-pink-400/40",
    buttonBg: "bg-pink-800/40",
    buttonHover: "hover:bg-pink-700/50",
    buttonText: "text-pink-100",
    inputBg: "bg-indigo-800/50",
    inputBorder: "border-pink-400/40",
    badgeBg: "bg-pink-600/50",
    badgeText: "text-pink-100",
    scrollHeaderBg: "bg-indigo-900/95",
    dropdownBg: "bg-indigo-950",
    linkHover: "hover:text-white",
    rarityColors: {
      "8/8": "bg-white text-pink-700 border-pink-200",
      "7/8": "bg-pink-200 text-pink-800 border-pink-300",
      "6/8": "bg-pink-300 text-pink-900 border-pink-400",
      "5/8": "bg-pink-400 text-white border-pink-500",
      "4/8": "bg-pink-500 text-white border-pink-600",
      "3/8": "bg-purple-400 text-white border-purple-500",
      "2/8": "bg-purple-500 text-white border-purple-600",
      "1/8": "bg-indigo-700 text-indigo-200 border-indigo-600",
    },
  },
  synthwave: {
    name: "Synthwave",
    background: "bg-gradient-to-b from-purple-900 to-blue-900",
    cardBg: "bg-purple-950/40",
    cardBorder: "border-cyan-400/30",
    headerBg: "bg-purple-950/60",
    textPrimary: "text-cyan-300",
    textSecondary: "text-cyan-400",
    textAccent: "text-fuchsia-400",
    border: "border-cyan-400/40",
    buttonBg: "bg-fuchsia-800/40",
    buttonHover: "hover:bg-fuchsia-700/50",
    buttonText: "text-fuchsia-100",
    inputBg: "bg-purple-950/50",
    inputBorder: "border-cyan-400/30",
    badgeBg: "bg-cyan-600/50",
    badgeText: "text-cyan-100",
    scrollHeaderBg: "bg-purple-950/95",
    dropdownBg: "bg-purple-950",
    linkHover: "hover:text-fuchsia-300",
    rarityColors: {
      "8/8": "bg-fuchsia-400 text-white border-fuchsia-300",
      "7/8": "bg-fuchsia-500 text-white border-fuchsia-400",
      "6/8": "bg-purple-500 text-white border-purple-400",
      "5/8": "bg-purple-600 text-white border-purple-500",
      "4/8": "bg-cyan-500 text-white border-cyan-400",
      "3/8": "bg-cyan-600 text-white border-cyan-500",
      "2/8": "bg-blue-600 text-white border-blue-500",
      "1/8": "bg-slate-700 text-slate-200 border-slate-600",
    },
  },
  bloodMoon: {
    name: "Blood Moon",
    background: "bg-gradient-to-tr from-black via-red-950 to-black",
    cardBg: "bg-red-950/20",
    cardBorder: "border-red-600/30",
    headerBg: "bg-black/30",
    textPrimary: "text-red-200",
    textSecondary: "text-red-400",
    textAccent: "text-white",
    border: "border-red-700/40",
    buttonBg: "bg-red-900/30",
    buttonHover: "hover:bg-red-800/40",
    buttonText: "text-red-100",
    inputBg: "bg-red-950/40",
    inputBorder: "border-red-700/40",
    badgeBg: "bg-red-800/50",
    badgeText: "text-red-100",
    scrollHeaderBg: "bg-black/95",
    dropdownBg: "bg-black",
    linkHover: "hover:text-white",
    rarityColors: {
      "8/8": "bg-red-500 text-white border-red-400",
      "7/8": "bg-red-600 text-white border-red-500",
      "6/8": "bg-red-700 text-white border-red-600",
      "5/8": "bg-red-800 text-white border-red-700",
      "4/8": "bg-red-900 text-white border-red-800",
      "3/8": "bg-red-950 text-white border-red-900",
      "2/8": "bg-gray-800 text-gray-300 border-gray-700",
      "1/8": "bg-gray-900 text-gray-400 border-gray-800",
    },
  },
  "8Bit": {
    name: "8-Bit",
    background: "bg-blue-900",
    cardBg: "bg-blue-800/40",
    cardBorder: "border-cyan-400/50",
    headerBg: "bg-blue-950/60",
    textPrimary: "text-white",
    textSecondary: "text-blue-300",
    textAccent: "text-yellow-300",
    border: "border-blue-700/60",
    buttonBg: "bg-blue-700/50",
    buttonHover: "hover:bg-blue-600/50",
    buttonText: "text-white",
    inputBg: "bg-blue-800/60",
    inputBorder: "border-blue-600/70",
    badgeBg: "bg-blue-600/70",
    badgeText: "text-blue-100",
    scrollHeaderBg: "bg-blue-950/95",
    dropdownBg: "bg-blue-950",
    linkHover: "hover:text-yellow-200",
    rarityColors: {
      "8/8": "bg-pink-500 text-white border-pink-400",
      "7/8": "bg-red-500 text-white border-red-400",
      "6/8": "bg-orange-500 text-white border-orange-400",
      "5/8": "bg-yellow-400 text-black border-yellow-300",
      "4/8": "bg-lime-400 text-black border-lime-300",
      "3/8": "bg-green-500 text-white border-green-400",
      "2/8": "bg-cyan-400 text-white border-cyan-300",
      "1/8": "bg-gray-500 text-white border-gray-400",
    },
  },
  cyberpunkCity: {
    name: "Cyberpunk City",
    background: "bg-gradient-to-b from-black via-blue-950 to-slate-900",
    cardBg: "bg-slate-800/20",
    cardBorder: "border-cyan-500/30",
    headerBg: "bg-black/40",
    textPrimary: "text-cyan-200",
    textSecondary: "text-blue-300",
    textAccent: "text-yellow-300",
    border: "border-cyan-400/40",
    buttonBg: "bg-cyan-800/30",
    buttonHover: "hover:bg-cyan-700/40",
    buttonText: "text-cyan-100",
    inputBg: "bg-slate-900/50",
    inputBorder: "border-cyan-500/40",
    badgeBg: "bg-yellow-600/30",
    badgeText: "text-yellow-200",
    scrollHeaderBg: "bg-black/95",
    dropdownBg: "bg-slate-950",
    linkHover: "hover:text-yellow-200",
    rarityColors: {
      "8/8": "bg-yellow-400 text-black border-yellow-300",
      "7/8": "bg-cyan-400 text-black border-cyan-300",
      "6/8": "bg-fuchsia-500 text-white border-fuchsia-400",
      "5/8": "bg-blue-500 text-white border-blue-400",
      "4/8": "bg-blue-600 text-white border-blue-500",
      "3/8": "bg-indigo-600 text-white border-indigo-500",
      "2/8": "bg-indigo-700 text-white border-indigo-600",
      "1/8": "bg-slate-700 text-slate-200 border-slate-600",
    },
  },
  oled: {
    name: "OLED Black",
    background: "bg-black",
    cardBg: "bg-zinc-950/40",
    cardBorder: "border-zinc-800/30",
    headerBg: "bg-black/95",
    textPrimary: "text-zinc-50",
    textSecondary: "text-zinc-400",
    textAccent: "text-cyan-400",
    border: "border-zinc-800/40",
    buttonBg: "bg-zinc-900/60",
    buttonHover: "hover:bg-zinc-800/60",
    buttonText: "text-zinc-100",
    inputBg: "bg-black/60",
    inputBorder: "border-zinc-800/40",
    badgeBg: "bg-zinc-800/50",
    badgeText: "text-zinc-50",
    scrollHeaderBg: "bg-black/98",
    dropdownBg: "bg-black",
    linkHover: "hover:text-cyan-300",
    rarityColors: {
      "8/8": "bg-cyan-500 text-black border-cyan-400",
      "7/8": "bg-purple-500 text-white border-purple-400",
      "6/8": "bg-blue-500 text-white border-blue-400",
      "5/8": "bg-green-500 text-white border-green-400",
      "4/8": "bg-yellow-500 text-black border-yellow-400",
      "3/8": "bg-orange-500 text-white border-orange-400",
      "2/8": "bg-red-500 text-white border-red-400",
      "1/8": "bg-zinc-700 text-zinc-300 border-zinc-600",
    },
  },
}

// ─── Utility Functions ─────────────────────────────────────────
export function parseValue(value: number | string): number {
  if (typeof value === "number") return value
  if (typeof value === "string") {
    if (value === "N/A") return 0
    if (value.includes("-")) {
      const parts = value.split("-").map((p) => Number.parseFloat(p.trim()))
      return (parts[0] + parts[1]) / 2
    }
    return Number.parseFloat(value) || 0
  }
  return 0
}

export function getTierLetter(tier: string | undefined): string {
  if (!tier) return "?"
  if (tier.startsWith("S")) return "S"
  if (tier.startsWith("A")) return "A"
  if (tier.startsWith("B")) return "B"
  if (tier.startsWith("C")) return "C"
  if (tier.startsWith("D")) return "D"
  if (tier.startsWith("E")) return "E"
  if (tier.startsWith("F")) return "F"
  if (tier.includes("Collect")) return "CT"
  if (tier.includes("Throw")) return "TB"
  if (tier.includes("Retex")) return "RT"
  if (tier.includes("Game")) return "GP"
  if (tier.includes("Obtain")) return "OB"
  return "?"
}

export function getTierColor(tier: string | undefined): string {
  if (!tier) return "text-gray-400"
  if (tier.startsWith("S")) return "text-red-400"
  if (tier.startsWith("A")) return "text-orange-400"
  if (tier.startsWith("B")) return "text-yellow-400"
  if (tier.startsWith("C")) return "text-green-400"
  if (tier.startsWith("D")) return "text-cyan-400"
  if (tier.startsWith("E")) return "text-blue-400"
  if (tier.startsWith("F")) return "text-indigo-400"
  if (tier.includes("Collect")) return "text-purple-400"
  if (tier.includes("Throw")) return "text-violet-400"
  if (tier.includes("Retex")) return "text-pink-400"
  if (tier.includes("Game")) return "text-fuchsia-400"
  if (tier.includes("Obtain")) return "text-amber-400"
  return "text-gray-400"
}

export function loadTheme(): string {
  if (typeof window === "undefined") return "dark"
  const urlParams = new URLSearchParams(window.location.search)
  const urlTheme = urlParams.get("theme")
  if (urlTheme && themes[urlTheme]) return urlTheme
  const saved = localStorage.getItem("dinosaur-value-list-theme")
  if (saved && themes[saved]) return saved
  return "dark"
}

export function saveTheme(themeName: string) {
  localStorage.setItem("dinosaur-value-list-theme", themeName)
  const url = new URL(window.location.href)
  url.searchParams.set("theme", themeName)
  window.history.replaceState({}, "", url.toString())
}

// ─── All Dinosaurs (flat list for calculator) ──────────────────
export const allDinosaurs: Dinosaur[] = [
  // S Tier (110+)
  { name: "Eschaton Argentinosaurus", value: 650, rarity: "8/8", tier: "S" },
  { name: "Apparition Fossil Giganotosaurus", value: 550, rarity: "8/8", tier: "S" },
  { name: "Pitch Wraith Terror", value: 285, rarity: "7/8", tier: "S" },
  { name: "Pitchygator", value: 220, rarity: "8/8", tier: "S" },
  { name: "Wraith Terror", value: 180, rarity: "6/8", tier: "S" },
  { name: "Hydralania", value: 165, rarity: "7/8", tier: "S" },
  { name: "Distorted King", value: 160, rarity: "8/8", tier: "S" },
  { name: "Blue Whale Shastasaurus", value: 155, rarity: "6/8", tier: "S" },
  { name: "Violex Magnus", value: 145, rarity: "6/8", tier: "S" },
  { name: "Fallen Gladiator", value: 135, rarity: "6/8", tier: "S" },
  { name: "Pitch Black Moray Oxalaia", value: 130, rarity: "7/8", tier: "S" },
  { name: "Berserk Alametus", value: 125, rarity: "6/8", tier: "S" },
  // A Tier (50-109)
  { name: "Albino Terror", value: 100, rarity: "8/8", tier: "A" },
  { name: "Megavore", value: 100, rarity: "8/8", tier: "A" },
  { name: "Isisauriraptor", value: 100, rarity: "6/8", tier: "A" },
  { name: "Galactic Barosaurus", value: 98, rarity: "7/8", tier: "A" },
  { name: "Cathedral Fasolatherium", value: 97, rarity: "6/8", tier: "A" },
  { name: "Nameless Barosaurus", value: 90, rarity: "6/8", tier: "A" },
  { name: "Orca Spinosaurus", value: 80, rarity: "6/8", tier: "A" },
  { name: "Movie Mosasaurus", value: 70, rarity: "6/8", tier: "A" },
  { name: "Giant Albino Baryonyx", value: 70, rarity: "6/8", tier: "A" },
  { name: "Reaper Gelioichthys", value: 67, rarity: "6/7", tier: "A" },
  { name: "Dolphin Ichthyovenator", value: 65, rarity: "6/8", tier: "A" },
  { name: "Aurora Borethalass", value: 60, rarity: "6/8", tier: "A" },
  { name: "Pitch Black Terror", value: 60, rarity: "6/8", tier: "A" },
  { name: "Kaiju Giraffatitan", value: 56, rarity: "6/8", tier: "A" },
  { name: "Zomvinychus", value: 55, rarity: "6/8", tier: "A" },
  { name: "Pitch Luminescent Avinychus", value: 52, rarity: "5/8", tier: "A" },
  // B Tier (25-49)
  { name: "Luminescent Avinychus", value: 48, rarity: "5/8", tier: "B" },
  { name: "Pitch Coconut Brachiosaurus", value: 40, rarity: "4/8", tier: "B" },
  { name: "Scylla", value: 38, rarity: "5/8", tier: "B" },
  { name: "Kaiju Spinofaarus", value: 38, rarity: "5/8", tier: "B" },
  { name: "Spinofaarus", value: 36, rarity: "5/8", tier: "B" },
  { name: "Phantom Bringer Ceratosaurus", value: 35, rarity: "4/8", tier: "B" },
  { name: "Classic Pitch Black Terror", value: 35, rarity: "4/8", tier: "B" },
  { name: "Crossover Hybrid/Vinera", value: 33, rarity: "5/8", tier: "B" },
  { name: "Firebird", value: 32, rarity: "6/8", tier: "B" },
  { name: "Carcharocles Megalodon", value: 30, rarity: "6/8", tier: "B" },
  { name: "Butterfly Alametus", value: 30, rarity: "6/8", tier: "B" },
  { name: "Peak Spinosaurus", value: 28, rarity: "6/8", tier: "B" },
  { name: "Spawn Shunosaurus", value: 27, rarity: "6/8", tier: "B" },
  { name: "Spectre Fossil Megavore", value: 27, rarity: "4/8", tier: "B" },
  { name: "Reindeer Istiodactylus", value: 27, rarity: "3/8", tier: "B" },
  { name: "Forgotten Mutant", value: 26, rarity: "5/8", tier: "B" },
  { name: "Kaiju Gelioichthys", value: 26, rarity: "5/8", tier: "B" },
  // C Tier (15-25)
  { name: "Early Winter Frost Sauroposeidon", value: 25, rarity: "4/8", tier: "C" },
  { name: "Toy Train Mastodonsaurus", value: 24, rarity: "5/8", tier: "C" },
  { name: "Alpha Kaiju Spinosaurus", value: 24, rarity: "5/8", tier: "C" },
  { name: "Disco Stegosaurus", value: 24, rarity: "4/8", tier: "C" },
  { name: "Pitch Black Apatosaurus", value: 24, rarity: "4/8", tier: "C" },
  { name: "Pitch Black Dolichomalosaurus", value: 23, rarity: "4/8", tier: "C" },
  { name: "Rakebaby Guanlong", value: 22, rarity: "4/8", tier: "C" },
  { name: "Gold Fossil Giganotosaurus", value: 22, rarity: "3/8", tier: "C" },
  { name: "White Walker Carcharodontosaurus", value: 20, rarity: "4/8", tier: "C" },
  { name: "Headlessaurus", value: 19, rarity: "4/8", tier: "C" },
  { name: "Krampus", value: 19, rarity: "4/8", tier: "C" },
  { name: "Alien Irritator", value: 19, rarity: "4/8", tier: "C" },
  { name: "Totem Terror Albertosaurus", value: 18, rarity: "4/8", tier: "C" },
  { name: "Spring Blossom Lusotitan", value: 18, rarity: "4/8", tier: "C" },
  { name: "Phoenix Achillobator", value: 18, rarity: "3/8", tier: "C" },
  { name: "Masquerade Gigantoraptor", value: 18, rarity: "4/8", tier: "C" },
  { name: "Indomitable Thief Gen 2", value: 17, rarity: "4/8", tier: "C" },
  { name: "Cyber Ichthyovenator", value: 17, rarity: "3/8", tier: "C" },
  { name: "Coconut Brachiosaurus", value: 15, rarity: "3/8", tier: "C" },
  // D Tier (10-14)
  { name: "Indomitable King", value: 14, rarity: "4/8", tier: "D" },
  { name: "Santa Clawz", value: 14, rarity: "3/8", tier: "D" },
  { name: "Movie Giganotosaurus", value: 14, rarity: "3/8", tier: "D" },
  { name: "Kralkatorrik", value: 14, rarity: "2/8", tier: "D" },
  { name: "Movie Therizinosaurus", value: 14, rarity: "2/8", tier: "D" },
  { name: "Frosteological Skelewyvern Quetzalcoatlus", value: 13, rarity: "4/8", tier: "D" },
  { name: "Abandoned Matriarch", value: 13, rarity: "4/8", tier: "D" },
  { name: "Gold Fossil Tyrannosaurus", value: 13, rarity: "3/8", tier: "D" },
  { name: "Chaos Titanosaur", value: 13, rarity: "3/8", tier: "D" },
  { name: "Gold Fossil Spinosaurus", value: 13, rarity: "2/8", tier: "D" },
  { name: "Pitch Black Shantungosaurus", value: 12, rarity: "3/8", tier: "D" },
  { name: "Miresteed Baryonyx", value: 12, rarity: "4/8", tier: "D" },
  { name: "Gold Lily Saurolophus", value: 12, rarity: "2/8", tier: "D" },
  { name: "Cozy Cabin Argentinosaurus", value: 10, rarity: "3/8", tier: "D" },
  { name: "Kaiju Sauroposeidon", value: 10, rarity: "3/8", tier: "D" },
  { name: "Nidhogg Purrrusaurus", value: 10, rarity: "3/8", tier: "D" },
  { name: "Lil UFO Pteranodon", value: 10, rarity: "2/8", tier: "D" },
  // E Tier (4-9)
  { name: "Kaiju Titanosaurus", value: 9, rarity: "3/8", tier: "E" },
  { name: "Singulafaarus", value: 9, rarity: "3/8", tier: "E" },
  { name: "Violex Parvulus", value: 9, rarity: "3/8", tier: "E" },
  { name: "Snowflake Stegosaurus", value: 9, rarity: "2/8", tier: "E" },
  { name: "Heartracer Concavenator", value: 9, rarity: "2/8", tier: "E" },
  { name: "Clamarocles Megalodon", value: 9, rarity: "2/8", tier: "E" },
  { name: "Mayhem Gojirasaurus", value: 9, rarity: "2/8", tier: "E" },
  { name: "Saurophaganax Remodel", value: 8, rarity: "3/8", tier: "E" },
  { name: "Blinding White Shantungosaurus", value: 8, rarity: "2/8", tier: "E" },
  { name: "Night Before Cretaceous", value: 8, rarity: "2/8", tier: "E" },
  { name: "Blackodile", value: 8, rarity: "2/8", tier: "E" },
  { name: "Movie Brachiosaurus", value: 8, rarity: "2/8", tier: "E" },
  { name: "Apatosaurus Plush", value: 8, rarity: "2/8", tier: "E" },
  { name: "Putrefied Amargasaurus", value: 8, rarity: "2/8", tier: "E" },
  { name: "Fossil Spinosaurus", value: 7.5, rarity: "2/8", tier: "E" },
  { name: "Kaiju Archelon", value: 7, rarity: "3/8", tier: "E" },
  { name: "The Mimic", value: 7, rarity: "3/8", tier: "E" },
  { name: "Indomitable Thief", value: 7, rarity: "3/8", tier: "E" },
  { name: "Fossil Baryonyx", value: 7, rarity: "2/8", tier: "E" },
  { name: "Movie Spinosaurus", value: 7, rarity: "2/8", tier: "E" },
  { name: "Polar Grazer Puertasaurus", value: 7, rarity: "2/8", tier: "E" },
  { name: "Psychoceratops", value: 7, rarity: "1/8", tier: "E" },
  { name: "Fossil Cadger", value: 6, rarity: "3/8", tier: "E" },
  { name: "Kaiju Quetzalcoatlus", value: 6, rarity: "2/8", tier: "E" },
  { name: "Radiated Zomvinychus", value: 6, rarity: "1/8", tier: "E" },
  { name: "Bogmire Suchomimus", value: 6, rarity: "1/8", tier: "E" },
  { name: "Movie Spinofaarus", value: 5, rarity: "3/8", tier: "E" },
  { name: "Fossil Megavore", value: 5, rarity: "2/8", tier: "E" },
  { name: "Sunfish Shonisaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Chaos Spinosaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Movie Triceratops", value: 5, rarity: "2/8", tier: "E" },
  { name: "Yeti Albertosaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Christmas Shunosaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Chaos Mosasaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Acrocanthorse", value: 5, rarity: "2/8", tier: "E" },
  { name: "Flying Dutchman", value: 5, rarity: "2/8", tier: "E" },
  { name: "Tree Elder Ankylosaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Movie Pyroraptor", value: 5, rarity: "2/8", tier: "E" },
  { name: "Forest Dweller Shantungosaurus", value: 5, rarity: "2/8", tier: "E" },
  { name: "Steelforged Concavenator", value: 5, rarity: "1/8", tier: "E" },
  { name: "Juramaia", value: 5, rarity: "1/8", tier: "E" },
  { name: "Barosaurus Plush", value: 4.5, rarity: "1/8", tier: "E" },
  { name: "Galactic Torvosaurus", value: 4, rarity: "2/8", tier: "E" },
  { name: "Voodoo Murusraptor", value: 4, rarity: "2/8", tier: "E" },
  { name: "Canyon Finback Suchomimus", value: 4, rarity: "2/8", tier: "E" },
  { name: "Neon Pulverizer Concavenator", value: 4, rarity: "2/8", tier: "E" },
  { name: "Sneaky Bunny Guanlong", value: 4, rarity: "2/8", tier: "E" },
  { name: "Monarch Meganeura", value: 4, rarity: "2/8", tier: "E" },
  { name: "Infected Camarasaurus", value: 4, rarity: "2/8", tier: "E" },
  { name: "Honey Heist Gigatitan", value: 4, rarity: "2/8", tier: "E" },
  { name: "Collector Maip Macrothorax", value: 4, rarity: "2/8", tier: "E" },
  { name: "Vampire Batzegopteryx", value: 4, rarity: "1/8", tier: "E" },
  { name: "Gold Fossil Skulker", value: 4, rarity: "2/8", tier: "E" },
  { name: "Nomad Corythosaurus", value: 4, rarity: "1/8", tier: "E" },
  { name: "Possessed Troodon", value: 4, rarity: "1/8", tier: "E" },
  // F Tier (0-4)
  { name: "Gargoyle Hatzegopteryx", value: 3.5, rarity: "2/8", tier: "F" },
  { name: "Kaiju Helicoprion", value: 3.5, rarity: "2/8", tier: "F" },
  { name: "Kaiju Baryonyx", value: 3, rarity: "2/8", tier: "F" },
  { name: "Classified Troodon", value: 3, rarity: "2/8", tier: "F" },
  { name: "Galactic Gallimimus", value: 3, rarity: "2/8", tier: "F" },
  { name: "Movie Baryonyx", value: 3, rarity: "2/8", tier: "F" },
  { name: "Rakefather Amargasaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Pitch Black Plateosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Galactic Hatzegopteryx", value: 3, rarity: "1/8", tier: "F" },
  { name: "Pitch Black Avimimus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Pop Candy Pachycephalosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Fluffle Therizinosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Fossil Thalassomedon", value: 3, rarity: "1/8", tier: "F" },
  { name: "Fossil Giganotosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Old Bark Nomad Corythosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Pristine Vessel Nomad Corythosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Sky High Nomad Corythosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Tiderider Nomad Corythosaurus", value: 3, rarity: "1/8", tier: "F" },
  { name: "Pumpkin Megalodon", value: 3, rarity: "1/8", tier: "F" },
  { name: "Scarecrow Thanatosdrakon", value: 3, rarity: "1/8", tier: "F" },
  { name: "Yang Tide", value: 3, rarity: "1/8", tier: "F" },
  { name: "Yin Flare", value: 3, rarity: "1/8", tier: "F" },
  { name: "Mammoth", value: 2.5, rarity: "2/8", tier: "F" },
  { name: "Galactic Euoplocephalus", value: 2.5, rarity: "1/8", tier: "F" },
  { name: "Ornament Utahraptor", value: 2.5, rarity: "1/8", tier: "F" },
  { name: "Glutton Elk Spinofaarus", value: 2.5, rarity: "1/8", tier: "F" },
  { name: "Galactic Fresnosaurus", value: 2.25, rarity: "1/8", tier: "F" },
  { name: "Twilight Pliosaurus", value: 2.25, rarity: "1/8", tier: "F" },
  { name: "Movie Gallimimus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Novel Carnotaurus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Movie Ceratosaurus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Movie Quetzalcoatlus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Movie Dilophosaurus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Maceball Stegosaurus", value: 2, rarity: "2/8", tier: "F" },
  { name: "Blinding White Dodo", value: 2, rarity: "2/8", tier: "F" },
  { name: "Pitch Black Megalodon", value: 2, rarity: "2/8", tier: "F" },
  { name: "Chaos Tyrannosaurus Rex", value: 2, rarity: "2/8", tier: "F" },
  { name: "Movie Ankylosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Hot Cocoa Ichthyovenator", value: 2, rarity: "1/8", tier: "F" },
  { name: "Tundra Grazer Triceratops", value: 2, rarity: "2/8", tier: "F" },
  { name: "Bone Eating Hibbertopterus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Bloodwurm Tullimonstrum", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Brachiosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Carcharocles Megalodon", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Sarcosuchus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Mosasaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Tyrannosaurus Rex", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Utahraptor", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Pteranodon", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Onchopristis", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Ornithomimus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fallen Caveman", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Acrocanthosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Basilosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Therizinosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Fossil Skulker", value: 2, rarity: "1/8", tier: "F" },
  { name: "Easter Gallimimus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Valley Golem Machimosaurus", value: 2, rarity: "1/8", tier: "F" },
  { name: "Christmas Dodo", value: 2, rarity: "1/8", tier: "F" },
  { name: "Christmas Stegoceras", value: 2, rarity: "1/8", tier: "F" },
  { name: "Universal Dilophosaurus", value: 1.75, rarity: "1/8", tier: "F" },
  { name: "Nutcracker Wanderer", value: 1.75, rarity: "2/8", tier: "F" },
  { name: "Charybdis", value: 1.75, rarity: "1/8", tier: "F" },
  { name: "Movie Hatzegopteryx", value: 1.5, rarity: "2/8", tier: "F" },
  { name: "Stocking Gojirasaurus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Candycane Kentrosaurus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Terror Bunny Allosaurus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Santa Guard Mammoth", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Lovebug Thalassodromeus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Dreamhaze Fresnosaurus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Swan Deinocheirus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Megafraud", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Manticore", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Zeus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Thor", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "The Kraken", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Tartrap Spinosaurus", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Kaiju Triceratops", value: 1.5, rarity: "1/8", tier: "F" },
  { name: "Movie Pachycephalosaurus", value: 1, rarity: "2/8", tier: "F" },
  { name: "Movie Stegosaurus", value: 1, rarity: "2/8", tier: "F" },
  { name: "Movie Compsognathus", value: 1, rarity: "2/8", tier: "F" },
  { name: "Movie Tyrannosaurus Rex", value: 1, rarity: "1/8", tier: "F" },
  { name: "Cottontail Maiasaura", value: 1, rarity: "1/8", tier: "F" },
  { name: "Makeship Triceratops", value: 1, rarity: "1/8", tier: "F" },
  { name: "Movie Velociraptor", value: 1, rarity: "1/8", tier: "F" },
  { name: "Movie Parasaurolophus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Movie Allosaurus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Movie Carnotaurus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Movie Pteranodon", value: 1, rarity: "1/8", tier: "F" },
  { name: "Frosted Rex", value: 1, rarity: "1/8", tier: "F" },
  { name: "Clay Iguanodon", value: 1, rarity: "1/8", tier: "F" },
  { name: "Classified Tylosaurus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Drinking Bird Gigantoraptor", value: 1, rarity: "1/8", tier: "F" },
  { name: "DNA Raptor", value: 1, rarity: "1/8", tier: "F" },
  { name: "Chicken Egg Balaur", value: 1, rarity: "1/8", tier: "F" },
  { name: "Christmas Coelacanth", value: 1, rarity: "1/8", tier: "F" },
  { name: "Gingerbread Ichthyosaurus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Chimerasuchus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Fallen Excavator", value: 1, rarity: "1/8", tier: "F" },
  { name: "Overseer Wanderer", value: 1, rarity: "1/8", tier: "F" },
  { name: "Late Valentines Plush", value: 1, rarity: "1/8", tier: "F" },
  { name: "Snow Globe Megalodon", value: 1, rarity: "1/8", tier: "F" },
  { name: "Santa Ornithomimus", value: 1, rarity: "1/8", tier: "F" },
  { name: "Spider Troodon", value: 1, rarity: "1/8", tier: "F" },
  { name: "Cetus", value: 0.75, rarity: "1/8", tier: "F" },
  { name: "Hestiaceras", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Cerberus", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Griffin", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Balure", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Minotaurus", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Kentrallos", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Harpydactylus", value: 0.5, rarity: "1/8", tier: "F" },
  { name: "Erymanthian Styracoboar", value: 0.5, rarity: "1/8", tier: "F" },
  // Collectors' Tier
  { name: "Branded Purrusaurus", value: "2800-3200", rarity: "1/8", tier: "Collectors'" },
  { name: "Metron Praenintius", value: "1700-1900", rarity: "2/8", tier: "Collectors'" },
  { name: "Pitch Black Sunfish Shonisaurus", value: 245, rarity: "6/8", tier: "Collectors'" },
  { name: "Pitch Black Elasmosaurus", value: 225, rarity: "6/8", tier: "Collectors'" },
  { name: "Pitch Black Baryonyx", value: 190, rarity: "2/8", tier: "Collectors'" },
  { name: "Golden Ectenosaurus", value: "150-300", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Fasolatherium", value: "240-260", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Albino Terror", value: "220-240", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Dolichomalosaurus", value: "200-220", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Gelioichthys", value: "200-220", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Megavore", value: "180-190", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Avinychus", value: "170-190", rarity: "1/8", tier: "Collectors'" },
  { name: "Grayscale Alametus", value: "160-170", rarity: "1/8", tier: "Collectors'" },
  { name: "Classic Albino Terror", value: "25-28", rarity: "3/8", tier: "Collectors'" },
  { name: "Classic Megavore", value: "25-28", rarity: "3/8", tier: "Collectors'" },
  { name: "Diamond Tusoteuthis", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Acrocanthosaurus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Shunosaurus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Maiasaurus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Styracosaurus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Pteranodon", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Thalassodromeus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Parasaurolophus", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Concavenator", value: 10, rarity: "1/8", tier: "Collectors'" },
  { name: "Diamond Gojirasaurus", value: 10, rarity: "1/8", tier: "Collectors'" },
  // Throwbacks
  { name: "Prebivaropus", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Avinychus", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Gelioichthys", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Dolichomalasaurus", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Fasolatherium", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Alametus", value: 2, rarity: "2/8", tier: "Throwbacks" },
  { name: "Throwback Barosaurus", value: 1.5, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Argentinosaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Carcharocles Megalodon", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Mapusaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Basilosaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Spinofaarus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Yutyrannus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Barinasuchus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Shantungosaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Dunkleosteus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Purussaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Chimerarachne", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Suchomimus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Majungasaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Pachycephalosaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Jackelopterus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Tiktaalik", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Gigatitan", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Tullimonstrum", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Hibbertopterus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Fasolasuchus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Arizonasaurus", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Anomalocaris", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Opabinia", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Callichimaera", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Meganeura", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  { name: "Throwback Trilobite", value: 0.1, rarity: "1/8", tier: "Throwbacks" },
  // Retextures
  { name: "Diamond Albino Terror", value: 6, rarity: "2/8", tier: "Retextures" },
  { name: "Diamond Megavore", value: 6, rarity: "2/8", tier: "Retextures" },
  { name: "Diamond Barosaurus", value: 5, rarity: "1/8", tier: "Retextures" },
  { name: "Rainbow Albino Terror", value: 6, rarity: "2/8", tier: "Retextures" },
  { name: "Rainbow Megavore", value: 6, rarity: "2/8", tier: "Retextures" },
  { name: "Rainbow Barosaurus", value: 2, rarity: "1/8", tier: "Retextures" },
  { name: "ALL Glass skins", value: 0.25, rarity: "1/8", tier: "Retextures" },
  // Gamepasses
  { name: "Classic Pitch Black Terror V4", value: 5, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Krampus", value: 3, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Headlessaurus", value: 2, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Fossil Brachiosaurus", value: 1, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Megavore V3", value: 1, rarity: "2/8", tier: "Gamepasses" },
  { name: "Classic Albino Terror V4", value: 1, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Psychoceratops", value: 1, rarity: "1/8", tier: "Gamepasses" },
  { name: "Classic Pitch Black Terror V3", value: 5, rarity: "2/8", tier: "Gamepasses" },
  { name: "Classic Albino Terror V3", value: 5, rarity: "2/8", tier: "Gamepasses" },
  { name: "Kaiju Spinosaurus", value: 5, rarity: "1/8", tier: "Gamepasses" },
  { name: "Riot Shield Triceratops", value: 3, rarity: "1/8", tier: "Gamepasses" },
  { name: "Icicle Styracosaurus", value: 2, rarity: "1/8", tier: "Gamepasses" },
  { name: "Albino T-Rex", value: 1.5, rarity: "1/8", tier: "Gamepasses" },
  { name: "Scarred T-Rex", value: 1.5, rarity: "1/8", tier: "Gamepasses" },
  // Obtainables
  { name: "Permian Excavator", value: 4, rarity: "1/8", tier: "Obtainables" },
  { name: "Ultimallosaurus", value: 2, rarity: "1/8", tier: "Obtainables" },
  { name: "Apex Hothead Megavore", value: 2, rarity: "1/8", tier: "Obtainables" },
  { name: "Solar Bringer Megavore", value: 0.5, rarity: "1/8", tier: "Obtainables" },
  { name: "Deep Sea Megavore", value: 0.5, rarity: "1/8", tier: "Obtainables" },
  { name: "Zweinova-Blank", value: 7.5, rarity: "2/8", tier: "Obtainables" },
  { name: "Zenova", value: 5, rarity: "2/8", tier: "Obtainables" },
  { name: "Dimension Beast", value: 5, rarity: "1/8", tier: "Obtainables" },
  { name: "Withered Willow Futalognkosaurus", value: 0, rarity: "1/8", tier: "Obtainables" },
  { name: "Crow Istiodactylus", value: 0, rarity: "1/8", tier: "Obtainables" },
  { name: "Raven Hatzegopteryx", value: 0, rarity: "1/8", tier: "Obtainables" },
  { name: "Wyvern", value: 0, rarity: "1/8", tier: "Obtainables" },
  { name: "Yutashu", value: 0, rarity: "1/8", tier: "Obtainables" },
]
